data_path: null
dropout: 0.0
encoding_dim: 32
features:
- latitude
- longitude
- altitude
- timedelta
h_dims: []
info_features: []
info_index: null
lr: 0.001
lr_gamma: 1.0
lr_step_size: 100
max_epochs: 10
network_name: MyAE
