data_path: null
dropout: 0.0
encoding_dim: 64
features:
- latitude
- longitude
- altitude
- timedelta
h_dims:
- 512
- 216
info_features: []
info_index: null
lr: 0.001
lr_gamma: 1.0
lr_step_size: 100
max_epochs: 500
network_name: MyAE
