data_path: null
dropout: 0.0
encoding_dim: 32
features:
- latitude
- longitude
- altitude
- timedelta
fix_prior: true
h_dims:
- 64
info_features: []
info_index: null
kld_coef: 1.0
llv_coef: 1.0
lr: 0.001
lr_gamma: 1.0
lr_step_size: 100
max_epochs: 500
n_components: 3
network_name: MyVAE
scale: 1.0
